from flask import Flask
import json
import random
app = Flask(__name__)

batFightWords = [
    "AIEEE!",
    "AIIEEE!",
    "ARRGH!",
    "AWK!",
    "AWKKKKKK!",
    "BAM!",
    "BANG!",
    "BANG-ETH!",
    "BIFF!",
    "BLOOP!",
    "BLURP!",
    "BOFF!",
    "BONK!",
    "CLANK!",
    "CLANK-EST!",
    "CLASH!",
    "CLUNK!",
    "CLUNK-ETH!",
    "CRRAACK!",
    "CRASH!",
    "CRRAACK!",
    "CRUNCH!",
    "CRUNCH-ETH!",
    "EEE-YOW!",
    "FLRBBBBB!",
    "GLIPP!",
    "GLURPP!",
    "KAPOW!",
    "KAYO!",
    "KER-SPLOOSH!",
    "KERPLOP!",
    "KLUNK!",
    "KLONK!",
    "KRUNCH!",
    "OOOFF!",
    "OOOOFF!",
    "OUCH!",
    "OUCH-ETH!",
    "OWWW!",
    "OW-ETH",
    "PAM!",
    "PLOP!",
    "POW!",
    "POWIE!",
    "QUNCKKK!",
    "RAKKK!",
    "RIP!",
    "SLOSH!",
    "SOCK!",
    "SPLATS!",
    "SPLATT!",
    "SPLOOSH!",
    "SWAAP!",
    "SWISH!",
    "SWOOSH!",
    "THUNK!",
    "THWACK!",
    "THWACKE!",
    "THWAPE!",
    "THWAPP!",
    "UGGH!",
    "URKKK!",
    "VRONK!",
    "WHACK!",
    "WHACK-ETH!",
    "WHAM-ETH!",
    "WHAMM!",
    "WHAMMM!",
    "WHAP!",
    "Z-ZWAP!",
    "ZAM!",
    "ZAMM!",
    "ZAMMM!",
    "ZAP!",
    "ZAP-ETH",
    "ZGRUPPP!",
    "ZLONK!",
    "ZLOPP!",
    "ZLOTT!",
    "ZOK!",
    "ZOWIE!",
    "ZWAPP!",
    "ZZWAP!",
    "ZZZZWAP!",
    "ZZZZZWAP!"]

@app.route('/')
def getword():  # put application's code here
    word = random.choice(batFightWords)
    payload = { "batFightWord": word,
                "batFighworkImageUrl" : "TODO" }
    return json.dumps(payload)
@app.route('/word')
def getwordonly():  # put application's code here
    return random.choice(batFightWords)

if __name__ == '__main__':
    app.run()
